version: '3'
networks:
  quarkus_net:
    external: true
services:

  # Bases de donnée
  app-quarkus-db:
    build:
      context: ./app-quarkus-db/
    image: shipstone/app-quarkus-db:1.0
    container_name: app-quarkus-db
    ports:
      - 5432:5432
    networks:
      - quarkus_net
