version: '3'
networks:
  quarkus_net:
    external: true

services:
  # Bases de donnée
  db:
    build:
      context: docker/app-quarkus-db
    image: sihm/db:1.0
    container_name: demo-db
    ports:
      - 5432:5432
    networks:
      - quarkus_net

  # ping
  ping-spring-jvm:
    build:
      context: ping-spring
      dockerfile: src/main/docker/Dockerfile.jvm.multi
    image: sihm/ping-spring-jvm:1.0
    container_name: ping-spring-jvm
    ports:
      - 8087:8087
    networks:
      - quarkus_net
  ping-quarkus-jvm:
    build:
      context: ping-quarkus
      dockerfile: src/main/docker/Dockerfile.jvm.multi
    image: sihm/ping-quarkus-jvm:1.0
    container_name: ping-quarkus-jvm
    ports:
      - 8096:8086
    networks:
      - quarkus_net
  ping-quarkus-native:
    build:
      context: ping-quarkus
      dockerfile: src/main/docker/Dockerfile.native.multi
    image: sihm/ping-quarkus-native:1.0
    container_name: ping-quarkus-native
    ports:
      - 8086:8086
    networks:
      - quarkus_net

  # City
  city-spring-jvm:
    build:
      context: city-spring
      dockerfile: src/main/docker/Dockerfile.jvm.multi
    image: sihm/city-spring-jvm:1.0
    container_name: city-spring-jvm
    ports:
      - 8085:8080
    links:
      - db
    depends_on:
      - db
    networks:
      - quarkus_net
  city-quarkus-jvm:
    build:
      context: city-quarkus
      dockerfile: src/main/docker/Dockerfile.jvm.multi
    image: sihm/city-quarkus-jvm:1.0
    container_name: city-quarkus-jvm
    ports:
      - 8094:8080
    links:
      - db
    depends_on:
      - db
    networks:
      - quarkus_net
  city-quarkus-native:
    build:
      context: city-quarkus
      dockerfile: src/main/docker/Dockerfile.native.multi
    image: sihm/city-quarkus-native:1.0
    container_name: city-quarkus-native
    ports:
      - 8084:8080
    links:
      - db
    depends_on:
      - db
    networks:
      - quarkus_net
