apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ping-quarkus-jvm
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: ping-quarkus-jvm
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: ping-quarkus-jvm
  name: ping-quarkus-jvm
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ping-quarkus-jvm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ping-quarkus-jvm
    spec:
      containers:
      - image: sihm/ping-quarkus-jvm:1.0
        name: ping-quarkus-jvm
        ports:
        - containerPort: 8080
        resources: {}
status: {}
## TODO : Ajouter city
## TODO : Ajouter person
